# Generated by Django 5.0.7 on 2024-07-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tablecell',
            unique_together={('row', 'column')},
        ),
    ]
