# Generated by Django 5.0.7 on 2024-07-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_tablecolumn_sum_value_alter_tablecell_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablecolumn',
            name='sum_value',
        ),
        migrations.AddField(
            model_name='tablerow',
            name='sum_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
